# Site settings
name: Nicole Chen
title: Nicole Chen | Student
description: a user-centric product engineer and student driven by a humility in learning from others balanced by a confidence in her own ideals. 
url: https://nchen55555.github.io/
baseurl: ''
email: nicole_chen@college.havard.edu
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/student.png
resume: https://nchen55555.github.io/resume.pdf
social:
  - title: email
    url: mailto:nicole_chen@college.harvard.edu
  - title: twitter
    url: https://twitter.com/bchiang7
  - title: instagram
    url: https://instagram.com/bchiang7
  - title: codepen
    url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/bchiang7
  - title: linkedin
    url: https://www.linkedin.com/in/bchiang7

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
